### ISSUE TITLE
Group members are removed when group display name is changed

### ISSUE THREAD

**Issue by xaviarias** [osiam/osiam#95] opened 2015-12-22 16:37 UTC
After changing a group's display name, all its members disappear.

**Comment by wallner** [comment] 2015-12-23 00:09
Hello @xaviarias,
thank you for reporting this. Could you please elaborate what you were doing so that we can reproduce it? We don't really support PATCH'ing of resources, so if you use PUT to update the `diplayName` of a group, you still need to provide the list of its members.

**Comment by xaviarias** [comment] 2015-12-24 11:18
Hi @wallner,

The steps to reproduce are user and group creation, adding user membership and changing the group's display name.

All those steps are made through the addon-administration web application, so no HTTP methods are involved through our direct interaction.

**Comment by wallner** [comment] 2015-12-26 23:08
Hello @xaviarias,
sorry for the delay, I was away on Christmas & family duty. I hope you had a very good time too. Now to something different: I'm afraid I can't reproduce your bug. Can you please tell me which combination of versions you are using? (addon-administration, auth-server and resource-server or osiam 3, which is not released yet) We would really like to help you here!

**Comment by xaviarias** [comment] 2015-12-28 09:56
Hello @wallner, thanks hope you had a good time too. 

The steps are very straight, in the addon administration console (I'm using OSIAM Docker image) I create a group with a display name and external ID, then I create a new user and add it to the group. Then I change the display name of the group, and the recently added user disappears from its member list.

Please confirm if you are being able to reproduce. It also happens on release v2.4.

**Comment by wallner** [comment] 2015-12-29 15:36
Hello @xaviarias,
you are right. This is a bug. I'm sorry for the inconvenience we are causing with it. We are looking into it and are going to provide a fix soon.

**Comment by wallner** [comment] 2015-12-29 15:45
Das Problem scheint im Patching der Gruppe zu liegen.

**Comment by wallner** [comment] 2016-01-02 15:44
This is a bug in the addon-addministration component. Therefore I open one there (osiam/addon-administration#119) to track it and close this one here if that's all right for everybody.

**Closed as completed by wallner** 2016-01-02 15:44 UTC
Labels: bug
