### ISSUE TITLE
Customize 'osiam' for usecase 'Publish your app's API with OSIAM'

### ISSUE THREAD

**Issue by nileshpa** [osiam/osiam#300] opened 2017-04-26 20:08 UTC
Hi,  
 I am SCIM beginner and looking for SCIM server to publish our App managed entities like user, groups... This project is very promising and well maintained. 
I am looking for some guidance on how to customize the server to be able to fetch entities from our custom data service.
Looking at the code probably I need to implement ResourceDao service.  Is there any documentation I can follow on how to achieve this? Thank you.

**Comment by tkrille** [comment] 2017-05-14 15:20
Hello @nileshpa,

first of all, I have to clarify some things:

1. OSIAM's role is not to publish users and groups of your application and converting them to SCIM. OSIAM is an IAM (Identity and Access Management) and has its own notions of entities like users and groups and it owns, maintains and persists them on its own. In this sense, OSIAM publishes entities like users and roles to be consumed by your application(s) (and possibly third parties). It does so with the use of SCIM's schemas and protocols. You can say that the SCIM part of OSIAM is the 'I' in IAM.

2. The use case, you are referring to, does mean something else: It means to allow third party apps to consume you're application's API on behalf of your users without knowing their login credentials. This has actually nothing to do with SCIM. It's something that is realized by OAuth 2, the second standard OSIAM is built upon. You can say that this use case is realized by the 'A' in IAM.

Nevertheless, you're not the first one who wants to use OSIAM more like a SCIM server framework. Another user had a [similar question](https://github.com/osiam/osiam/issues/256). If this somehow resembles you're use case, please comment on the issue.

> Looking at the code probably I need to implement ResourceDao service. Is there any documentation I can follow on how to achieve this?

So you want to build your own "fork" of OSIAM, that fetches user and group data from your application instead of a SQL database? Then swapping `ResourceDao` with your own implementation seems like a reasonable thing to do. But this is not supported by us in any way. And no, we don't have any documentation on this either. We're currently thinking about this "OSIAM as a framework" thing. There are occasional discussions about this in Slack. But we don't have any kind of roadmap or specific vision for it.

I'm closing this for now, as I think it is a duplicate of #256.

**Closed as completed by tkrille** 2017-05-14 15:20 UTC
Labels: duplicate
